# [ec2]
# myec2 ansible_host=15.206.95.1

# [ec2:vars]
# ansible_user=ubuntu
# ansible_ssh_private_key_file=~/.ssh/Home-Key.pem


[ec2]
15.206.95.1 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Home-Key.pem


# test connectivity with:
# ansible all -i inventory.ini -m ping

# ansible ec2 -i inventory.ini -m ping
